version: '3.8'

services:
    nginx:
        build: ./nginx
        ports:
            - 1337:80
        depends_on:
            - cnp
        volumes:
            - ./static/:/usr/src/app/static/
        networks:
            - net_inner

    cnp:
        build: ./cnp_project
        restart: always
        entrypoint:
            - /usr/src/app/entrypoint-project.sh
        command: ['gunicorn', 'cnp.wsgi:application', '--bind', '0.0.0.0:8080']
        volumes:
            - ./static/:/usr/src/app/staticfiles/
        expose:
            - 8080
        env_file:
            - ./env.project
        depends_on:
            - db
        networks:
            - net_inner

    db:
        image: postgres:12.0-alpine
        restart: always
        volumes:
            - ./postgres-data/:/var/lib/postgresql/data/
        env_file:
            - ./env.db
        networks:
            - net_inner

networks:
    net_inner:
        driver: bridge
