version: '3.8'

services:
    cnp:
        build: ./cnp_project
        restart: always
        entrypoint:
            - /usr/src/app/entrypoint-project.sh
        command: python3 manage.py runserver 0.0.0.0:8000
        volumes:
            - ./cnp_project/:/usr/src/app/
        ports:
            - 8000:8000
        env_file:
            - ./env.project
        depends_on:
            - db
        networks:
            - net_inner

    db:
        image: postgres:12.0-alpine
        restart: always
        volumes:
            - postgres_data:/var/lib/postgresql/data/
        env_file:
            - ./env.db
        networks:
            - net_inner

volumes:
    postgres_data:

networks:
    net_inner:
        driver: bridge
